language: node_js
sudo: false
node_js:
- '8.9'
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  app:
    master: moovin-hackathon-orange01
  api_key:
    secure: 1fBP0ilkbLBeLkcNmpFgC9CLwUwT0w49nlwCS5hVx3QybiktpmX8ZXlXLAealms9jZm25rCkkx9R6oN+3xBa9LYXrmZxlyzMhJFV2p5oKANNZsWb0EVUXFbK/AskE7DF50uZlhIvoy3CMLiN2PvrAjE3o7cKS19vNClLjjwiyrjhyHI0hyAgV4TxOo51GnOsleIYtIRl+Mk2tBsNeOiLETJwThPBLpOk/mgIyHEvn6y7O6+TsA2/CI4TdbVvhXojgdMpitoMbwehDId5qQ97AXvlq8xh2AZSlcPgAK6gVKSDBNARxluZ8Tl5Q3Bn11qCA5Xjxq6ASi7tNcvi/8GGQ261FPKfqTE7bhkJqbk1vPgmJdaryolZ9wT+XQNYg81pE18gVcT3PgHt9GZVyHhrFtbD75poN0SIYqFtdmZvaguV4CiLuMvw7lvfJ7qGWytJ1gauAzH6OjV69rbiA5dDkjd2p9F9MueQsMqs7sKguStZ9IAj7qemW6STmxezbAV2AMLKvh+ySN3CEclAsF5wewlOjKyxDurogmtP3f4fgLrwHCCYJh8rtPeVws9FGj9kxU1exQjnQZRPvfj9/qoMBpjI23fG0En3wtSLzQVLKOxGR6rH2YGVdMqieaJeZB1ikNxtDAX42ARGl/Ro16zv1ynwml/Gw/lgh5+RBu3k0Uk=
